### PR TITLE
fix: remove double headers on conceptual pages

### PR DESCRIPTION
**Pull request by dandhlee**
On conceptual pages, there were cases where two titles would show up, one originating from 

`{{{rawTitle}}}` from `conceptual.html.primary.tmpl`, 

and the other from `<h1 class="page-title">{{#title}}{{title}}{{/title}}{{^title}}{{>partials/title}}{{/title}}</h1>` 
 snippet from `layout/_master.tmpl`.

Moving this to ManagedRefenrece and UniversalReference templates fixes the double headers issue but devsite complains with the following message:

```
DevSite page must have a non-empty <title> tag, a non-empty <h1 class="page-title"> tag, or provide <meta name="no_page_title" value="true" />.
```

since the conceptual page titles come pre-rendered with the HTML tags, I think the best way to go with this is to add a `meta` field for conceptual pages. The added `meta` field only shows up on the conceptual pages which had double headers issue, removing the second header but allowing the original `rawTitle` html to show.

Fixes internal issue

### CODE REVIEW

**Comment by dandhlee** [comment]
Verified the fix on 
[go conceptual page](https://github.com/googleapis/doc-templates/pull/131/files#diff-544e5243b4459e47af1fba59ac1c2f688859f9d042601b88f8af719f44c44832) as well as on dotnet locally.

**Comment by dandhlee** [comment]
Adding "do not merge" label until further improvements are made, as all elements in headers are sanitized and thus this method won't work.

**Comment by dandhlee** [comment]
so devsite gives 3 options.
1) DevSite page must have a non-empty <title> tag
- this does not work, as `<title>` elements go inside `<head>` and all of the content inside `<head>` gets sanitized.

2) provide <meta name="no_page_title" value="true" />
- this does not work either, same reason as above

3) non-empty <h1 class="page-title"> tag

the only icky thing is that the `{{{rawTitle}}}` content already come rendered as h1 or h2 elements, how do we feel about wrapping the title within the tag above? i.e.
```
<h1 class="page-title">
  {{{rawTitle}}}
</h1>
```
which looks like
```
//dotnet config page
<h1 class="page-title">
    <h1 id="configuration">Configuration</h1>
</h1>
```
or 
```
//go pgk-readme page
<h1 class="page-title">
    <h2 id="cloud-storage-godochttpsgodocorgcloudgooglecomgostoragestatussvghttpsgodocorgcloudgooglecomgostorage">Cloud Storage <a href="https://godoc.org/cloud.google.com/go/storage"><img src="https://godoc.org/cloud.google.com/go/storage?status.svg" alt="GoDoc"></a></h2>
</h1>
```

Although wrapped around by the h1 tag, it seem to look fine on [Go](https://cloud.devsite.corp.google.com/dotnet/docs/reference/Google.Cloud.Spanner.Data/latest/configuration)

**Comment by dandhlee** [comment]
It seems that alternate images and links attached to an `h1` elements gets stripped away.

Nesting inside a `h1 title` element looks fine on [Go](https://cloud.devsite.corp.google.com/go/docs/reference/cloud.google.com/go/storage/latest/pkg-readme), but it will get stripped of its alternate image and link attached that exists in the original code.

**Comment by dandhlee** [comment]
@tbpg ready for review, PTAL!

**Review by tbpg — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
