### PR TITLE
cleanup: adding Node.js golden tests

### LINKED ISSUE #31: docfx: add Node.js golden test
We should add Node.js goldens. We have some right now for Python, Go, and .NET. "Goldens" are used to very changes we make to the templates look OK in the HTML. We have some tests that check particular things (the HTML should contain this string, etc.), but the goldens check the output doesn't change unless we want it to.

1. Copy Node.js YAML into the `testdata` directory.
1. Add that directory here: https://github.com/googleapis/doc-templates/blob/61b4bdeb99c6ff51e7ec8a569be2f4bd2c7805f9/tests/test_goldens.py#L25-L28
1. [Generate the goldens](https://github.com/googleapis/doc-templates#testing).
1. Confirm the HTML looks OK.
1. Run the tests to verify they pass.

### PR DESCRIPTION
**Pull request by dandhlee**
Included scheduler api from Node.js as golden test candidate

Fixes #31

### CODE REVIEW

**Review by tbpg — APPROVED** [review]
Thanks!

@fhinkel FYI

**Comment by fhinkel** [comment]
thanks!

**Comment by fhinkel** [comment]
FYI, pretty sure that tarball lacks the actual scheduler API and only includes other protos.

**Comment by dandhlee** [comment]
@tbpg will this be an issue for now? If not I suppose we can grab a proper tarball later that does include an API. If it is, @fhinkel what tarball could I use?

**Comment by tbpg** [comment]
It's easy to update in the future. So, I think having something is better than nothing.

Maybe we should update it when we fix #83.

**Comment by dandhlee** [comment]
Sounds good.

**Pull request merged**
